# -*- coding: utf-8 -*-
"""Industryassignment2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1LUrQhHUl4q2l-FqzAK5sGAl9tUWpMLms
"""

import pandas as pd
df=pd.read_csv('/content/drive/MyDrive/AI project/weatherAUS.csv')
df.head()
df.tail(40)
a=40,0
type(a)
df[['Date','Location']].max()

df.info()

df.use_inf_as_na = True

df.isnull().sum()

df1=df.drop_duplicates()

df1=df1.drop(['Date','Location','RainTomorrow'],axis='columns')

print(df1)

df[['Date','Location']].max()

# Commented out IPython magic to ensure Python compatibility.
import matplotlib.pyplot as plt
# %matplotlib inline
import numpy as np
df[['Date','Location']].plot(figsize=(9,7))

pip install pmdarima
import warnings
import pmdarima
from pmdarima import auto_arima
p_values = [0, 1, 2, 4, 6, 8, 10]
d_values = range(0, 3)
q_values = range(0, 3)
warnings.filterwarnings("ignore")
stepwise_fit=auto_arima(df['Date'],trace=True,suppress_warnings=True)

# evaluate parameters
import warnings
import pmdarima
from pmdarima import auto_arima
p_values = [0, 1, 2, 4, 6, 8, 10]
d_values = range(0, 3)
q_values = range(0, 3)
warnings.filterwarnings("ignore")
stepwise_fit=auto_arima(df['Date'],trace=True,suppress_warnings=True)

pip install pmdarima

from pandas import datetime
from pandas import read_csv
from pandas import DataFrame
import numpy as np
from statsmodels.tsa.arima.model import ARIMA
from matplotlib import pyplot
df = read_csv('/content/drive/MyDrive/AI project/weatherAUS.csv', header=0, index_col=0, parse_dates=True, squeeze=True)
df.index = df.index.to_period('M')
# fit model
model = ARIMA(df['Rainfall'])
model_fit = model.fit()
# summary of fit model
print(model_fit.summary())
# line plot of residuals
residuals = DataFrame(model_fit.resid)
residuals.plot()
pyplot.show()
# density plot of residuals
residuals.plot(kind='kde')
pyplot.show()
# summary stats of residuals
print(residuals.describe())



from pandas import datetime
from pandas import read_csv
from pandas import DataFrame
import numpy as np
from statsmodels.tsa.arima.model import ARIMA
from matplotlib import pyplot
df = read_csv('/content/drive/MyDrive/AI project/weatherAUS.csv', header=0, index_col=0, parse_dates=True, squeeze=True)
df.index = df.index.to_period('M')
# fit model
model = ARIMA(df, order=(5,1,0))
model_fit = model.fit()
# summary of fit model
print(model_fit.summary())
# line plot of residuals
residuals = DataFrame(model_fit.resid)
residuals.plot()
pyplot.show()
# density plot of residuals
residuals.plot(kind='kde')
pyplot.show()
# summary stats of residuals
print(residuals.describe())

